/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChannelTypeEnum,
  ChannelTypeEnum$inboundSchema,
  ChannelTypeEnum$outboundSchema,
} from "./channeltypeenum.js";
import {
  PreferenceOverrideSourceEnum,
  PreferenceOverrideSourceEnum$inboundSchema,
  PreferenceOverrideSourceEnum$outboundSchema,
} from "./preferenceoverridesourceenum.js";

export type PreferenceOverride = {
  /**
   * Channel type through which the message is sent
   */
  channel: ChannelTypeEnum;
  /**
   * The source of the override
   */
  source: PreferenceOverrideSourceEnum;
};

/** @internal */
export const PreferenceOverride$inboundSchema: z.ZodType<
  PreferenceOverride,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel: ChannelTypeEnum$inboundSchema,
  source: PreferenceOverrideSourceEnum$inboundSchema,
});

/** @internal */
export type PreferenceOverride$Outbound = {
  channel: string;
  source: string;
};

/** @internal */
export const PreferenceOverride$outboundSchema: z.ZodType<
  PreferenceOverride$Outbound,
  z.ZodTypeDef,
  PreferenceOverride
> = z.object({
  channel: ChannelTypeEnum$outboundSchema,
  source: PreferenceOverrideSourceEnum$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PreferenceOverride$ {
  /** @deprecated use `PreferenceOverride$inboundSchema` instead. */
  export const inboundSchema = PreferenceOverride$inboundSchema;
  /** @deprecated use `PreferenceOverride$outboundSchema` instead. */
  export const outboundSchema = PreferenceOverride$outboundSchema;
  /** @deprecated use `PreferenceOverride$Outbound` instead. */
  export type Outbound = PreferenceOverride$Outbound;
}

export function preferenceOverrideToJSON(
  preferenceOverride: PreferenceOverride,
): string {
  return JSON.stringify(
    PreferenceOverride$outboundSchema.parse(preferenceOverride),
  );
}

export function preferenceOverrideFromJSON(
  jsonString: string,
): SafeParseResult<PreferenceOverride, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreferenceOverride$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreferenceOverride' from JSON`,
  );
}
