/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PreferenceChannelsDto,
  PreferenceChannelsDto$inboundSchema,
  PreferenceChannelsDto$Outbound,
  PreferenceChannelsDto$outboundSchema,
} from "./preferencechannelsdto.js";
import {
  PreferenceOverride,
  PreferenceOverride$inboundSchema,
  PreferenceOverride$Outbound,
  PreferenceOverride$outboundSchema,
} from "./preferenceoverride.js";
import {
  WorkflowInfoDto,
  WorkflowInfoDto$inboundSchema,
  WorkflowInfoDto$Outbound,
  WorkflowInfoDto$outboundSchema,
} from "./workflowinfodto.js";

export type WorkflowPreferenceDto = {
  /**
   * Whether notifications are enabled for this workflow
   */
  enabled: boolean;
  /**
   * Channel-specific preference settings for this workflow
   */
  channels: PreferenceChannelsDto;
  /**
   * List of preference overrides
   */
  overrides: Array<PreferenceOverride>;
  /**
   * Workflow information
   */
  workflow: WorkflowInfoDto;
};

/** @internal */
export const WorkflowPreferenceDto$inboundSchema: z.ZodType<
  WorkflowPreferenceDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean(),
  channels: PreferenceChannelsDto$inboundSchema,
  overrides: z.array(PreferenceOverride$inboundSchema),
  workflow: WorkflowInfoDto$inboundSchema,
});

/** @internal */
export type WorkflowPreferenceDto$Outbound = {
  enabled: boolean;
  channels: PreferenceChannelsDto$Outbound;
  overrides: Array<PreferenceOverride$Outbound>;
  workflow: WorkflowInfoDto$Outbound;
};

/** @internal */
export const WorkflowPreferenceDto$outboundSchema: z.ZodType<
  WorkflowPreferenceDto$Outbound,
  z.ZodTypeDef,
  WorkflowPreferenceDto
> = z.object({
  enabled: z.boolean(),
  channels: PreferenceChannelsDto$outboundSchema,
  overrides: z.array(PreferenceOverride$outboundSchema),
  workflow: WorkflowInfoDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowPreferenceDto$ {
  /** @deprecated use `WorkflowPreferenceDto$inboundSchema` instead. */
  export const inboundSchema = WorkflowPreferenceDto$inboundSchema;
  /** @deprecated use `WorkflowPreferenceDto$outboundSchema` instead. */
  export const outboundSchema = WorkflowPreferenceDto$outboundSchema;
  /** @deprecated use `WorkflowPreferenceDto$Outbound` instead. */
  export type Outbound = WorkflowPreferenceDto$Outbound;
}

export function workflowPreferenceDtoToJSON(
  workflowPreferenceDto: WorkflowPreferenceDto,
): string {
  return JSON.stringify(
    WorkflowPreferenceDto$outboundSchema.parse(workflowPreferenceDto),
  );
}

export function workflowPreferenceDtoFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowPreferenceDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkflowPreferenceDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowPreferenceDto' from JSON`,
  );
}
