import { EditorView } from '@uiw/react-codemirror';

export const variablePillTheme = EditorView.baseTheme({
  '.cm-variable-pill': {
    backgroundColor: 'hsl(var(--bg-weak))',
    color: 'hsl(var(--text-sub))',
    border: '1px solid hsl(var(--stroke-soft))',
    borderRadius: '9999px',
    padding: '2px 6px 2px 18px',
    margin: '0 4px',
    fontFamily: 'inherit',
    display: 'inline-flex',
    alignItems: 'center',
    height: '16px',
    lineHeight: '16px',
    fontSize: '12px',
    cursor: 'pointer',
    position: 'relative',
    marginRight: '0px',
  },
  '.cm-variable-pill.has-modifiers': {
    paddingRight: '12px',
  },
  '.cm-variable-pill::before': {
    content: '""',
    position: 'absolute',
    left: '4px',
    top: '50%',
    transform: 'translateY(-50%)',
    width: '12px',
    height: '12px',
    backgroundColor: 'hsl(var(--feature-base))',
    maskImage: `url("/images/code.svg")`,
    maskRepeat: 'no-repeat',
    maskPosition: 'center',
    maskSize: 'contain',
    WebkitMaskImage: `url("/images/code.svg")`,
    WebkitMaskRepeat: 'no-repeat',
    WebkitMaskPosition: 'center',
    WebkitMaskSize: 'contain',
  },
  '.cm-variable-pill.has-modifiers::after': {
    content: '""',
    position: 'absolute',
    right: '5px',
    top: '50%',
    transform: 'translateY(-50%)',
    width: '4px',
    height: '4px',
    backgroundColor: 'hsl(var(--feature-base))',
    borderRadius: '50%',
  },
  '.cm-variable-pill.cm-dark': {
    backgroundColor: '#FFD6EE',
    color: '#AD74FF',
    border: '1px solid #3D3D4D',
  },
  '.cm-variable-pill.cm-dark.has-modifiers::after': {
    backgroundColor: '#AD74FF',
  },
  '.cm-variable-pill .cm-bracket': {
    display: 'none',
  },
  '.cm-content': {
    minHeight: '100%',
    display: 'flex',
    flexDirection: 'column',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
});
